backend:
  name: git-gateway
  branch: master
  squash_merges: true
  commit_messages:
    create: (cms) Create {{collection}} “{{slug}}”
    update: (cms) Update {{collection}} “{{slug}}”
    delete: (cms) Delete {{collection}} “{{slug}}”
    uploadMedia: (cms) Upload “{{path}}”
    deleteMedia: (cms) Delete “{{path}}”

media_folder: static/img
public_folder: /img

logo_url: https://cook.alexanders.xyz/img/logos/cook-b.svg

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

collections:
  - name: "pages"
    label: "Pages"
    folder: "pages"
    create: true
    slug: "{{path}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "page",
        }
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Path",
          name: "path",
          widget: "text",
          default: "{{year}}-{{month}}-{{day}}-{{slug}}",
        }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
      - {
          label: "Redirects",
          name: "redirects",
          widget: "list",
          required: false,
        }

  - name: "recipes"
    label: "Recipes"
    folder: "recipes"
    create: true
    slug: "{{path}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "project",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Path",
          name: "path",
          widget: "text",
          default: "{{year}}-{{month}}-{{day}}-{{slug}}",
        }
      - { label: "Order", name: "order", widget: "number" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Main Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - {
          label: "Redirects",
          name: "redirects",
          widget: "list",
          required: false,
        }

  - name: "notes"
    label: "Notes"
    folder: "notes"
    create: true
    slug: "{{path}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "note",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Path",
          name: "path",
          widget: "text",
          default: "{{year}}-{{month}}-{{day}}-{{slug}}",
        }
      - { label: "Main Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - {
          label: "Redirects",
          name: "redirects",
          widget: "list",
          required: false,
        }
